kind: Deployment
apiVersion: apps/v1
metadata:
  name: ubsi-admin-container
  #namespace: extension-ubsicontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubsi-admin-container
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubsi-admin-container
    spec:
      volumes:
        - name: consumer-config-volume
          configMap:
            name: ubsi-redis-conf
            defaultMode: 420
        - name: mongodb-config-volume
          configMap:
            name: ubsi-mongo-conf
            defaultMode: 420
        - name: ubsi-admin-logs-volume
          persistentVolumeClaim:
            claimName: ubsi-admin-container-logspvc
        - name: admin-license
          configMap:
            name: ubsi-admin-license
            defaultMode: 420
      
      containers:
        - name: ubsi-admin-container
          image: '{{ .Values.imageconall.repository }}:{{ .Values.imageconall.tag }}'
          ports:
            - containerPort: 7112
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: '-Xmx128m -Xms128m'
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
          volumeMounts:
          - name: consumer-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.consumer.json
            subPath: rewin.ubsi.consumer.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.script/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.eventflow/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.tester/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.flexible/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.repo/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.transaction/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.gateway/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.scheduler/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.user.session/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.logger/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.common.auditlog/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.common.dict/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.common.favor/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: mongodb-config-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.common.user/rewin.ubsi.mongodb.json
            subPath: rewin.ubsi.mongodb.json
          - name: ubsi-admin-logs-volume
            #readOnly: true
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.logs
          - name: admin-license
            mountPath: /opt/ubsi-admin-container/rewin.ubsi.modules/rewin.ubsi.admin/ubsi-admin-license.json
            subPath: ubsi-admin-license.json
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
