{{ if eq .Values.extEmbed "iframe" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: ubsipaas-cm-iframe
  namespace: extension-ubsipaas
data:
  index.js: |-
    System.register(["@kubed/components", "react"], (function (t, e) {
        var r = {},
            n = {};
        return {
            setters: [function (t) {
                r.Loading = t.Loading
            }, function (t) {
                n.default = t.default, n.useRef = t.useRef, n.useState = t.useState
            }],
            execute: function () {
                t(function () {
                    var t = {
                            122: function (t, e, r) {
                                var n = {
                                    "./base.json": 146
                                };

                                function o(t) {
                                    var e = i(t);
                                    return r(e)
                                }

                                function i(t) {
                                    if (!r.o(n, t)) {
                                        var e = new Error("Cannot find module '" + t + "'");
                                        throw e.code = "MODULE_NOT_FOUND", e
                                    }
                                    return n[t]
                                }

                                o.keys = function () {
                                    return Object.keys(n)
                                }, o.resolve = i, t.exports = o, o.id = 122
                            },
                            189: function (t, e, r) {
                                var n = {
                                    "./base.json": 941
                                };

                                function o(t) {
                                    var e = i(t);
                                    return r(e)
                                }

                                function i(t) {
                                    if (!r.o(n, t)) {
                                        var e = new Error("Cannot find module '" + t + "'");
                                        throw e.code = "MODULE_NOT_FOUND", e
                                    }
                                    return n[t]
                                }

                                o.keys = function () {
                                    return Object.keys(n)
                                }, o.resolve = i, t.exports = o, o.id = 189
                            },
                            725: function (t, e, r) {
                                var n = r(825).y;
                                e.w = function (t) {
                                    if (t || (t = 1), !r.y.meta || !r.y.meta.url) throw console
                                        .error("__system_context__", r.y), Error(
                                        "systemjs-webpack-interop was provided an unknown SystemJS context. Expected context.meta.url, but none was provided"
                                    );
                                    r.p = n(r.y.meta.url, t)
                                }
                            },
                            825: function (t, e, r) {
                                function n(t, e) {
                                    var r = document.createElement("a");
                                    r.href = t;
                                    for (var n = "/" === r.pathname[0] ? r.pathname : "/" + r.pathname,
                                             o = 0, i = n.length; o !== e && i >= 0;) {
                                        "/" === n[--i] && o++
                                    }
                                    if (o !== e) throw Error(
                                        "systemjs-webpack-interop: rootDirectoryLevel (" +
                                        e +
                                        ") is greater than the number of directories (" +
                                        o + ") in the URL path " + t);
                                    var u = n.slice(0, i + 1);
                                    return r.protocol + "//" + r.host + u
                                }

                                e.y = n;
                                var o = Number.isInteger || function (t) {
                                    return "number" == typeof t && isFinite(t) && Math.floor(
                                        t) === t
                                }
                            },
                            761: function (t) {
                                "use strict";
                                t.exports = r
                            },
                            726: function (t) {
                                "use strict";
                                t.exports = n
                            },
                            146: function (t) {
                                "use strict";
                                t.exports = {
                                    name: "Name"
                                }
                            },
                            941: function (t) {
                                "use strict";
                                t.exports = {
                                    name: "名称"
                                }
                            }
                        },
                        o = {};

                    function i(e) {
                        var r = o[e];
                        if (void 0 !== r) return r.exports;
                        var n = o[e] = {
                            exports: {}
                        };
                        return t[e](n, n.exports, i), n.exports
                    }

                    i.y = e, i.g = function () {
                        if ("object" == typeof globalThis) return globalThis;
                        try {
                            return this || new Function("return this")()
                        } catch (t) {
                            if ("object" == typeof window) return window
                        }
                    }(), i.o = function (t, e) {
                        return Object.prototype.hasOwnProperty.call(t, e)
                    }, i.r = function (t) {
                        "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(
                            t, Symbol.toStringTag, {
                                value: "Module"
                            }), Object.defineProperty(t, "__esModule", {
                            value: !0
                        })
                    },
                        function () {
                            var t;
                            i.g.importScripts && (t = i.g.location + "");
                            var e = i.g.document;
                            if (!t && e && (e.currentScript && (t = e.currentScript.src), !t)) {
                                var r = e.getElementsByTagName("script");
                                if (r.length)
                                    for (var n = r.length - 1; n > -1 && (!t || !/^http(s?):/.test(
                                        t));) t = r[n--].src
                            }
                            if (!t) throw new Error(
                                "Automatic publicPath is not supported in this browser");
                            t = t.replace(/#.*$/, "").replace(/\?.*$/, "").replace(/\/[^\/]+$/, "/"),
                                i.p = t
                        }();
                    var u = {};
                    return (0, i(725).w)(1),
                        function () {
                            "use strict";
                            i.r(u);
                            var t = i(726);

                            function e(t, e) {
                                (null == e || e > t.length) && (e = t.length);
                                for (var r = 0, n = Array(e); r < e; r++) n[r] = t[r];
                                return n
                            }

                            function r(t, r) {
                                return function (t) {
                                    if (Array.isArray(t)) return t
                                }(t) || function (t, e) {
                                    var r = null == t ? null : "undefined" != typeof Symbol &&
                                        t[Symbol.iterator] || t["@@iterator"];
                                    if (null != r) {
                                        var n, o, i, u, c = [],
                                            a = !0,
                                            s = !1;
                                        try {
                                            if (i = (r = r.call(t)).next, 0 === e) {
                                                if (Object(r) !== r) return;
                                                a = !1
                                            } else
                                                for (; !(a = (n = i.call(r)).done) && (c.push(n
                                                    .value), c.length !== e); a = !0) ;
                                        } catch (t) {
                                            s = !0, o = t
                                        } finally {
                                            try {
                                                if (!a && null != r.return && (u = r.return(),
                                                Object(u) !== u)) return
                                            } finally {
                                                if (s) throw o
                                            }
                                        }
                                        return c
                                    }
                                }(t, r) || function (t, r) {
                                    if (t) {
                                        if ("string" == typeof t) return e(t, r);
                                        var n = {}.toString.call(t).slice(8, -1);
                                        return "Object" === n && t.constructor && (n = t.constructor
                                            .name), "Map" === n || "Set" === n ? Array.from(
                                            t) : "Arguments" === n ||
                                        /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n) ?
                                            e(t, r) : void 0
                                    }
                                }(t, r) || function () {
                                    throw new TypeError(
                                        "Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."
                                    )
                                }()
                            }

                            var n = i(761);

                            function o() {
                                var e = r((0, t.useState)(!0), 2),
                                    o = e[0],
                                    i = e[1],
                                    u = (0, t.useRef)();
                                return t.default.createElement(t.default.Fragment, null, o && t.default
                                    .createElement(n.Loading, {
                                        className: "page-loading"
                                    }), t.default.createElement("iframe", {
                                    ref: u,
                                    src: "http://ubsipaas.{{ .Values.domain }}:{{ .Values.ingressPort }}",
                                    width: "100%",
                                    height: "100%",
                                    frameBorder: "0",
                                    style: {
                                        height: "calc(100vh - 68px)",
                                        display: o ? "none" : "block"
                                    },
                                    onLoad: function () {
                                        i(!1)
                                    }
                                }))
                            }

                            var c = [{
                                path: "/ubsipaas",
                                element: t.default.createElement(o, null)
                            }];

                            function a(t) {
                                return a = "function" == typeof Symbol && "symbol" == typeof Symbol
                                    .iterator ? function (t) {
                                    return typeof t
                                } : function (t) {
                                    return t && "function" == typeof Symbol && t.constructor ===
                                    Symbol && t !== Symbol.prototype ? "symbol" : typeof t
                                }, a(t)
                            }

                            function s(t) {
                                var e = function (t, e) {
                                    if ("object" != a(t) || !t) return t;
                                    var r = t[Symbol.toPrimitive];
                                    if (void 0 !== r) {
                                        var n = r.call(t, e || "default");
                                        if ("object" != a(n)) return n;
                                        throw new TypeError(
                                            "@@toPrimitive must return a primitive value.")
                                    }
                                    return ("string" === e ? String : Number)(t)
                                }(t, "string");
                                return "symbol" == a(e) ? e : e + ""
                            }

                            function f(t, e, r) {
                                return (e = s(e)) in t ? Object.defineProperty(t, e, {
                                    value: r,
                                    enumerable: !0,
                                    configurable: !0,
                                    writable: !0
                                }) : t[e] = r, t
                            }

                            function l(t, e) {
                                var r = Object.keys(t);
                                if (Object.getOwnPropertySymbols) {
                                    var n = Object.getOwnPropertySymbols(t);
                                    e && (n = n.filter((function (e) {
                                        return Object.getOwnPropertyDescriptor(t, e)
                                            .enumerable
                                    }))), r.push.apply(r, n)
                                }
                                return r
                            }

                            function p(t) {
                                for (var e = 1; e < arguments.length; e++) {
                                    var r = null != arguments[e] ? arguments[e] : {};
                                    e % 2 ? l(Object(r), !0).forEach((function (e) {
                                        f(t, e, r[e])
                                    })) : Object.getOwnPropertyDescriptors ? Object.defineProperties(
                                        t, Object.getOwnPropertyDescriptors(r)) : l(Object(r)).forEach(
                                        (function (e) {
                                            Object.defineProperty(t, e, Object.getOwnPropertyDescriptor(
                                                r, e))
                                        }))
                                }
                                return t
                            }

                            for (var y = i(189), b = y.keys().filter((function (t) {
                                return "./index.ts" !== t
                            })), m = {}, d = 0; d < b.length; d += 1) b[d].startsWith(".") && (
                                m = p(p({}, m), y(b[d])));
                            var v = m;

                            function h(t, e) {
                                var r = Object.keys(t);
                                if (Object.getOwnPropertySymbols) {
                                    var n = Object.getOwnPropertySymbols(t);
                                    e && (n = n.filter((function (e) {
                                        return Object.getOwnPropertyDescriptor(t, e)
                                            .enumerable
                                    }))), r.push.apply(r, n)
                                }
                                return r
                            }

                            function g(t) {
                                for (var e = 1; e < arguments.length; e++) {
                                    var r = null != arguments[e] ? arguments[e] : {};
                                    e % 2 ? h(Object(r), !0).forEach((function (e) {
                                        f(t, e, r[e])
                                    })) : Object.getOwnPropertyDescriptors ? Object.defineProperties(
                                        t, Object.getOwnPropertyDescriptors(r)) : h(Object(r)).forEach(
                                        (function (e) {
                                            Object.defineProperty(t, e, Object.getOwnPropertyDescriptor(
                                                r, e))
                                        }))
                                }
                                return t
                            }

                            for (var O = i(122), w = O.keys().filter((function (t) {
                                return "./index.ts" !== t
                            })), j = {}, S = 0; S < w.length; S += 1) w[S].startsWith(".") && (
                                j = g(g({}, j), O(w[S])));
                            var P = {
                                routes: c,
                                menus: [{
                                    parent: "{{ .Values.extParent }}",
                                    name: "ubsipaas",
                                    title: "{{ .Values.extTitle }}",
                                    icon: "cluster",
                                    order: 0,
                                    desc: "{{ .Values.extDesc }}",
                                    skipAuth: !0
                                }],
                                locales: {
                                    zh: v,
                                    en: j
                                }
                            };
                            globals.context.registerExtension(P)
                        }(), u
                }())
            }
        }
    }));

{{ end }}