{{- if eq .Values.architecture "standalone" }}
kind: Service
apiVersion: v1
metadata:
  {{- if .Values.service.name }}
  name: "{{ .Values.service.name }}"
  {{- else }}
  name: ubsi-mongo
  {{- end }}
  labels:
    {{- if .Values.service.name }}
    app: "{{ .Values.service.name }}"
    {{- else }}
    app: ubsi-mongo
    {{- end }}
  annotations:
    kubesphere.io/description: mongo service
spec:
  ports:
    - name: tcp-27017
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 31389
  selector:
    name: mongodb
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
{{- end }}