{{- if eq .Values.architecture "replicaset" }}
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379

---

apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name }}
  name: "{{ .Values.service.name }}-sentinel"
  {{- else }}
  name: redis-sentinel-svc
  {{- end }}
  labels:
    app: redis-sentinel
spec:
  selector:
    app: redis-sentinel
  ports:
  - name: redis
    port: 26379

{{- end }}