replicaCount: 1

imageconall:
  repository: registry.cn-hangzhou.aliyuncs.com/ubsi/ubsi-admin-container
  pullPolicy: Always
  tag: "1.0"
persistence:
  enabled: true
  #storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
ingressClass:
  name: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
service:
  type: ClusterIP
  port: 80
deployment:
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

