kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ubsi-admin
spec:
  {{ if .Values.ingressClass.name }}
  ingressClassName: {{ .Values.ingressClass.name }}
  {{- else }}
  ingressClassName: nginx
  {{- end }}
  rules:
    - host: rewin.ubsi.admin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-front-svc
                port:
                  number: 80
