kind: Deployment
apiVersion: apps/v1
metadata:
  name: ubsi-admin-front
  #namespace: extension-ubsicontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubsi-admin-front
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubsi-admin-front
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
            defaultMode: 420
      containers:
        - name: ubsi-admin-front-container
          image: 'registry.cn-hangzhou.aliyuncs.com/ubsi/admin-front:latest'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
