kind: Deployment
apiVersion: apps/v1
metadata:
  name: ubsi-gateway
  #namespace: extension-ubsicontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubsi-gateway
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubsi-gateway
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-exxwop
          configMap:
            name: ubsi-redis-conf
            defaultMode: 420
      containers:
        - name: ubsi-gateway
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          ports:
            - name: http-8090
              containerPort: 8090
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: '-Xmx256m -Xms256m'
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-exxwop
              readOnly: true
              mountPath: /opt/ubsi-gateway/rewin.ubsi.consumer.json
              subPath: rewin.ubsi.consumer.json
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
