{{- if eq .Values.architecture "replicaset" }}
{{- range $index, $e := until (int .Values.replicaCount) }}
apiVersion: v1
kind: Service
metadata:
  name: "ubsi-mongo-{{ $index }}" 
  labels:
    app: ubsi-mongo
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
  selector:
    statefulset.kubernetes.io/pod-name: ubsi-mongo-{{ $index }}
---
{{- end }}
{{- end }}