{{- if eq .Values.architecture "replicaset" }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name }}
  name: "{{ .Values.service.name }}"
  {{- else }}
  name: ubsi-mongo-svc
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ubsi-mongo
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
{{- end }} 